# Generated by Django 4.2.16 on 2024-10-27 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_rename_phone_number_employee_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Checkbox')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255)),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_app.customfield')),
                ('employeee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_app.employee')),
            ],
        ),
    ]
